### ISSUE TITLE
WELDER does incorrect thing

### ISSUE THREAD

**Issue by SteelCrow17** [jalu14/oath-rocalc#9]
checked with PS devs, it's supposed to reduce cast time by 10% but calc says 15%, and reads total DEX when it should read base

Once this is done the description in card.js should be updated so it no longer says [Missing Implementation] since it will be correct and acting as intended. I forgot to do that and I don't know how to edit my edit request.

**Comment by jalu14** [comment]
Thanks for pointing this out, I just deployed a fix for this now that I am updating the calc
